---
name: Delete Chronosphere Shaping Rules
on:
  workflow_dispatch:
    inputs:
      rollup_rules_delete_list:
        description: Chronosphere rollup rules to delete separated by ','
        type: string
        default: ''
        required: false
      drop_rules_delete_list:
        description: Chronosphere drop rules to delete separated by ','
        type: string
        default: ''
        required: false

env:
  SOURCE: ${{ github.workspace }}

defaults:
  run:
    shell: bash

jobs:
  delete_shaping_rules:
    name: Delete shaping rules
    runs-on:
      - ubuntu-latest
    env:
      CHRONOSPHERE_ORG_NAME: abnormal
      CHRONOSPHERE_API_TOKEN: ${{ secrets.CHRONOSPHERE_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Echo running command
        run: |
          echo 'bazel run --config=ci //projects/sre/chronosphere-tooling -- delete_shaping_rules --rollup-rules-delete-list "${{ inputs.rollup_rules_delete_list }}" --drop-rules-delete-list "${{ inputs.drop_rules_delete_list }}"'
