---
name: Delete Chronosphere Shaping Rules
on:
  workflow_dispatch:
inputs:
  rollup_rules_delete_list:
    description: Chronosphere rollup rules to delete separated by ','
    type: string
    default: ''
    required: true
  drop_rules_delete_list:
    description: Chronosphere drop rules to delete separated by ','
    type: string
    default: ''
    required: true

env:
  SOURCE: ${{ github.workspace }}

defaults:
  run:
    shell: bash

jobs:
  delete_shaping_rules:
    name: Delete shaping rules
    runs-on:
      - self-hosted
      - ci-prod-bzl-amd64
    env:
      CHRONOSPHERE_ORG_NAME: abnormal
      CHRONOSPHERE_API_TOKEN: ${{ secrets.CHRONOSPHERE_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Run bazel setup
        run: |
          # Boot a Bazel server as needed without runner process tracking
          RUNNER_TRACKING_ID="" && bazel info

      - name: Run sync rollup rules
        run: |
          bazel run --config=ci //projects/sre/chronosphere-tooling -- delete_shaping_rules --rollup-rules-delete-list ${{ inputs.rollup_rules_delete_list }} --drop-rules-delete-list ${{ inputs.drop_rules_delete_list }}
