name: Rerun orig.yml

on:
  workflow_run:
    workflows: [Demo]
    types:
      - completed

jobs:
  rerun_orig:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt < 3 }}
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rerun orig.yml
        run: |
          echo "Rerunning ..."

      - name: Get completed workflow jobs
        id: get_completed_jobs
        run: |
          jobs=$(
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.get_workflow_id.outputs.workflow_id }}/jobs" \
            | jq -r '.jobs[].id')
          echo "::set-output name=completed_jobs::$jobs"

      - name: Rerun completed jobs
        run: |
          for job_id in ${{ steps.get_completed_jobs.outputs.completed_jobs }}; do
            echo "Rerunning job with ID $job_id"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/jobs/$job_id/retry"
          done